---
- name: Install Node.js
  ansible.builtin.dnf:
    name: nodejs
    state: present
  when: languages.nodejs_development | default(false) | bool

- name: Install pnpm
  community.general.npm:
    name: pnpm
    global: true
    state: latest
  when: languages.nodejs_development | default(false) | bool

- name: Install yarn
  community.general.npm:
    name: yarn
    global: true
    state: latest
  when: languages.nodejs_development | default(false) | bool
