---
- name: Install Node.js
  ansible.builtin.dnf:
    name: nodejs
    state: present
  when: languages.nodejs_development | default(false) | bool

- name: Install pnpm
  community.general.npm:
    name: pnpm
    global: true
    state: latest
  when: languages.nodejs_development | default(false) | bool

- name: Install yarn
  community.general.npm:
    name: yarn
    global: true
    state: latest
  when: languages.nodejs_development | default(false) | bool

- name: Manage wrapper scripts
  ansible.builtin.include_role:
    name: internal/bin_wrapper
  vars:
    bin_wrapper_binaries: "{{ nodejs_development_binaries }}"
    bin_wrapper_enabled: "{{ languages.nodejs_development | default(false) | bool }}"
