---
host_runner_binaries:
  - flatpak
  - systemctl
  - podman
  - xdg-open
  - bootc
  - firefox
  - gh
  - skopeo
  - clamav
  - cosign

host_runner_enabled: "{{ tdx_host_runner_enabled | default(true) | bool }}"
