---
- name: Install C++ development packages
  ansible.builtin.dnf:
    name:
      - g++
      - gcc
      - gcc-c++
      - ctags
      - clangd
      - cmake
      - clang-devel
    state: present
  when: languages.cpp_development | default(false) | bool
