---
- name: Install Agent tools (goose)
  ansible.builtin.dnf:
    name:
      - goose
    state: present
  when: environments.agent | default(false) | bool

- name: Install OpenCode
  community.general.npm:
    name: opencode-ai
    state: present
    global: true
  when: environments.agent | default(false) | bool

- name: Install pi
  community.general.npm:
    name: "@earendil-works/pi-coding-agent"
    state: present
    global: true
  when: environments.agent | default(false) | bool

- name: Install omp
  community.general.npm:
    name: "@oh-my-pi/pi-coding-agent"
    state: present
    global: true
  when: environments.agent | default(false) | bool
