---
- name: Install .NET SDK and runtime
  ansible.builtin.dnf:
    name:
      - dotnet-sdk-10.0
      - dotnet-runtime-10.0
      - libicu
    state: present
  when: languages.dotnet_development | default(false) | bool
