---
- name: Install .NET SDK and runtime
  ansible.builtin.dnf:
    name:
      - dotnet-sdk-10.0
      - dotnet-runtime-10.0
      - libicu
    state: present
  when: languages.dotnet_development | default(false) | bool

- name: Manage wrapper scripts
  ansible.builtin.include_role:
    name: internal/bin_wrapper
  vars:
    bin_wrapper_binaries: "{{ dotnet_development_binaries }}"
    bin_wrapper_enabled: "{{ languages.dotnet_development | default(false) | bool }}"
