---
- name: Install Ruby packages
  ansible.builtin.dnf:
    name:
      - ruby
      - ruby-devel
      - rvm
    state: present
  when: languages.ruby_development | default(false) | bool

- name: Install Ruby LSP gems
  community.general.gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
  loop:
    - {name: ruby-lsp, version: "0.26.4"}
    - {name: ruby-lsp-rails, version: "0.4.8"}
    - {name: ruby-lsp-rspec, version: "0.1.28"}
    - {name: ruby-lsp-rubyfmt, version: "0.1.0"}
    - {name: ruby-lsp-rake, version: "0.3.6"}
  when: languages.ruby_development | default(false) | bool

- name: Manage wrapper scripts
  ansible.builtin.include_role:
    name: internal/bin_wrapper
  vars:
    bin_wrapper_binaries: "{{ ruby_development_binaries }}"
    bin_wrapper_enabled: "{{ languages.ruby_development | default(false) | bool }}"
