---
- name: Install Fedora packaging tools
  ansible.builtin.dnf:
    name:
      - fedpkg
      - packit
      - copr-cli
      - copr-rpmbuild
      - rust2rpm
      - go2rpm
      - cargo2rpm
      - pyp2spec
      - rubygem-gem2rpm
      - patch
      - tomcli
      - python3-pip
      - xxd
      - pyproject-rpm-macros
      - cargo-rpm-macros
    state: present
  when: environments.fedora_packaging | default(false) | bool

- name: Install Python packaging tools
  ansible.builtin.pip:
    name:
      - woolly
      - fuzzytail
      - cookiecutter
      - jinja2_time
    state: present
  when: environments.fedora_packaging | default(false) | bool

- name: Manage wrapper scripts
  ansible.builtin.include_role:
    name: internal/bin_wrapper
  vars:
    bin_wrapper_binaries: "{{ fedora_packaging_binaries }}"
    bin_wrapper_enabled: "{{ environments.fedora_packaging | default(false) | bool }}"
