---
- name: Install rustup and build tools
  ansible.builtin.dnf:
    name:
      - cargo
      - rust
      - rust-src
      - rust-analyzer
      - rustup
      - clang-devel
    state: present
  when: languages.rust_development | default(false) | bool
