---
- name: Install rustup and build tools
  ansible.builtin.dnf:
    name:
      - cargo
      - rust
      - rust-src
      - rust-analyzer
      - clang-devel
    state: present
  when: languages.rust_development | default(false) | bool

- name: Manage wrapper scripts
  ansible.builtin.include_role:
    name: internal/bin_wrapper
  vars:
    bin_wrapper_binaries: "{{ rust_development_binaries }}"
    bin_wrapper_enabled: "{{ languages.rust_development | default(false) | bool }}"
