---
- name: Install pyenv build dependencies
  ansible.builtin.dnf:
    name:
      - patch
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - tk-devel
      - libffi-devel
      - xz-devel
      - libuuid-devel
      - gdbm-libs
      - libnsl2
    state: present
  when: languages.python_development | default(false) | bool

- name: Install Python development packages
  ansible.builtin.dnf:
    name:
      - python3-devel
      - python3-pip
      - yamllint
      - ruff
      - pre-commit
    state: present
  when: languages.python_development | default(false) | bool

- name: Install pyright
  ansible.builtin.pip:
    name: pyright==1.1.407
    state: present
  when: languages.python_development | default(false) | bool

- name: Manage wrapper scripts
  ansible.builtin.include_role:
    name: internal/bin_wrapper
  vars:
    bin_wrapper_binaries: "{{ python_development_binaries }}"
    bin_wrapper_enabled: "{{ languages.python_development | default(false) | bool }}"
