---
base_binaries:
  - asciinema
  - fd
  - task
  - jq
  - make
  - rg
  - strace
  - nvim

base_packages:
  - asciinema
  - fd-find
  - task
  - fish
  - shfmt
  - fzf
  - git-credential-libsecret
  - jq
  - make
  - ripgrep
  - openssl-devel
  - g++
  - gcc
  - zstd
  - strace
  - ksshaskpass
  - git-lfs
  - nvim
