---
on:
  push:
    branches:
      - main
    paths:
      - 'Containerfile'
      - 'ansible/**'
      - 'hack/**'
      - 'bin/**'
      - '.github/workflows/**'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build Dev Toolbox
    uses: ./.github/workflows/build-image.yml
    with:
      context: .
      image: toolbox-dev
      containerfile: Containerfile
      push: true
    secrets: inherit
